USE T20ICRICKET;

SELECT 
    *
FROM
    T20I;

-- identify matches played between 2 specific teams in 2024 and their results(eg : india and south africa)

SELECT 
    TEAM1, TEAM2, WINNER, MATCHDATE
FROM
    T20I
WHERE
    (TEAM1 = 'INDIA'
        AND TEAM2 = 'SOUTH AFRICA')
        OR (TEAM1 = 'SOUTH AFRICA'
        AND TEAM2 = 'INDIA')
        AND YEAR(MATCHDATE) = 2024
ORDER BY MATCHDATE;

-- find the team with the highest number of wins in 2024 and the total matches it won. 
SELECT 
    WINNER,
    COUNT(*) AS NO_OF_WINS,
    YEAR(MATCHDATE) AS YEAR_OF_WIN
FROM
    T20I
WHERE
    YEAR(MATCHDATE) = 2024
GROUP BY WINNER , YEAR_OF_WIN
ORDER BY NO_OF_WINS DESC;

-- rank the teams based on the total number of wins in 2024
SELECT WINNER, NO_OF_WINS,
ROW_NUMBER() OVER(ORDER BY NO_OF_WINS DESC) AS WINNER_RANK
FROM
(
	SELECT WINNER, COUNT(*) AS NO_OF_WINS
    FROM T20I 
    WHERE YEAR(MATCHDATE) = 2024 AND WINNER NOT IN ('TIED', 'NO RESULT')
    GROUP BY WINNER
) t;

SELECT WINNER, COUNT(*) AS NO_OF_WINS,
DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS WINNER_RANK
FROM T20I 
WHERE YEAR(MATCHDATE) = 2024 AND WINNER NOT IN('TIED', 'NO RESULT')
GROUP BY WINNER;

-- which team has the highest average winning margin (in runs) and what was the average margin
SELECT 
    *
FROM
    T20I;

SELECT 
    WINNER, ROUND(AVG(MARGIN), 0) AS AVG_TEAM_MARGIN
FROM
    T20I
WHERE
    MARGIN LIKE '%RUNS'
GROUP BY WINNER
ORDER BY AVG_TEAM_MARGIN DESC;

-- list all matches where the winning margin was greater than the average margin across all matches

SELECT 
    WINNER, MARGIN
FROM
    T20I
WHERE
    MARGIN > (SELECT 
            AVG(MARGIN)
        FROM
            T20I
        WHERE
            MARGIN LIKE '%RUNS')
        AND MARGIN LIKE '%RUNS';
    
-- find the team with the most wins when chasing a target (wins by wickets)
SELECT WINNER, CHASING_WINS FROM (
SELECT WINNER, COUNT(*) AS CHASING_WINS,
RANK() OVER(ORDER BY COUNT(*) DESC) AS RK
FROM T20I 
WHERE MARGIN LIKE '%WICKETS' 
AND
WINNER NOT IN ('TIED' , 'NO RESULT')
GROUP BY WINNER
ORDER BY CHASING_WINS DESC) T
WHERE RK = 1;

-- head to head record between 2 selected teams
SELECT WINNER , COUNT(*) AS WINS
FROM T20I 
WHERE (TEAM1 = 'ENGLAND' AND TEAM2 = 'AUSTRALIA') 
OR (TEAM1 = 'AUSTRALIA' AND TEAM2 = 'ENGLAND')
GROUP BY WINNER;

-- identify the month in 2024 in which the highest number of T20 matches were played
SELECT MONTH(MATCHDATE) AS MONTH_NO, MONTHNAME(MATCHDATE)AS MONTH_NAME, COUNT(*) AS MATCHES_PLAYED
FROM T20I
WHERE YEAR(MATCHDATE) = 2024
GROUP BY MONTH(MATCHDATE), MONTHNAME(MATCHDATE)
ORDER BY MATCHES_PLAYED DESC;

-- for each team find how many matches they played in 2024 and their winning percentage
WITH COMBINED_TEAMS AS (
SELECT TEAM1 AS TEAM 
FROM T20I 
WHERE YEAR(MATCHDATE) = 2024
UNION ALL
SELECT TEAM2 AS TEAM 
FROM T20I 
WHERE YEAR(MATCHDATE) = 2024),

MATCHES_PLAYED AS(
SELECT TEAM, COUNT(*) AS MATCHES_PLAYED
FROM COMBINED_TEAMS
GROUP BY TEAM
),

TEAM_WINS AS (
SELECT WINNER AS TEAM,
COUNT(*) AS WINS
FROM T20I 
WHERE YEAR(MATCHDATE) = 2024
AND WINNER NOT IN ('TIED', 'NO RESULT')
GROUP BY WINNER)

SELECT M.TEAM, 
M.MATCHES_PLAYED,
W.WINS AS WINS,
ROUND(W.WINS * 100.0 / M.MATCHES_PLAYED , 2) AS WINNING_PERCENTAGE
FROM MATCHES_PLAYED M
LEFT JOIN TEAM_WINS W 
ON M.TEAM = W.TEAM
ORDER BY WINNING_PERCENTAGE DESC;

-- identify the most successful team at each ground (team with most wins per ground)
SELECT * FROM T20I;

SELECT GROUND, WINNER, COUNT(*) AS MATCHES_WON
FROM T20I 
GROUP BY GROUND , WINNER
ORDER BY MATCHES_WON DESC;

